name: Build All Robots

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        robot: [Princess, PAMI] #, PMI, PMX, Simu_F446, Simulation]
    continue-on-error: true
    outputs:
      sha: ${{ steps.vars.outputs.sha }}
      date: ${{ steps.vars.outputs.date }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          openocd \
          binutils-arm-none-eabi \
          gcc-arm-none-eabi \
          libnewlib-arm-none-eabi \
          libstdc++-arm-none-eabi-newlib \
          gdb-multiarch

    - name: Build firmware for ${{ matrix.robot }}
      run: make ROBOT=${{ matrix.robot }} all

    - name: Set version metadata
      id: vars
      run: |
        echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Package firmware
      run: |
        mkdir -p dist
        zip -r "dist/firmware-${{ matrix.robot }}.zip" "src/Robots/${{ matrix.robot }}"

    - name: Upload firmware archive
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{ matrix.robot }}
        path: dist/firmware-${{ matrix.robot }}.zip
        if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: release-assets

    - name: Set release tag
      run: |
        echo "RELEASE_TAG=${{ needs.build.outputs.date }}-${{ needs.build.outputs.sha }}" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: release-assets/firmware-*/*.zip
        tag_name: ${{ env.RELEASE_TAG }}
        name: Firmware Release ${{ env.RELEASE_TAG }}
        body: |
          ⚙️ Firmware build for all robots  
          ✅ Robots compilés avec succès : artefacts disponibles  
          ❌ Les échecs ne bloquent plus la release.
